# Production Docker Compose Configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up
version: '3.8'

services:
  frontend:
    environment:
      - NODE_ENV=production
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_FIREBASE_PROJECT_ID=ceremonial-tea-470904-f3
      - REACT_APP_FIREBASE_AUTH_DOMAIN=ceremonial-tea-470904-f3.firebaseapp.com
      - REACT_APP_FIREBASE_DATABASE_URL=https://ceremonial-tea-470904-f3-default-rtdb.firebaseio.com
      - REACT_APP_FIREBASE_STORAGE_BUCKET=ceremonial-tea-470904-f3.appspot.com

  backend:
    environment:
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=ceremonial-tea-470904-f3
      - FIREBASE_AUTH_DOMAIN=ceremonial-tea-470904-f3.firebaseapp.com
      - FIREBASE_DATABASE_URL=https://ceremonial-tea-470904-f3-default-rtdb.firebaseio.com
      - FIREBASE_STORAGE_BUCKET=ceremonial-tea-470904-f3.appspot.com
      # Firebase service account credentials should be set via secrets/environment variables
      # - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      # - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      # - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      # - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      # - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      # - JWT_SECRET=${JWT_SECRET}
      # - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      # - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes: []  # Remove development volume mounts in production