name: Bug Report
description: Report a bug or issue with yoohoo.guru
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      description: Please check all the boxes below before submitting your bug report.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I am using the latest version of yoohoo.guru
          required: true
        - label: I have read the contributing guidelines
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of the application is affected?
      options:
        - Frontend/UI
        - Backend/API
        - Authentication
        - Skill Matching
        - Payments
        - Database
        - Mobile/Responsive
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g. Chrome 119, Safari 17, Firefox 120
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: e.g. Windows 11, macOS 14, Ubuntu 22.04
    validations:
      required: true