name: Feature Request
description: Suggest a new feature for yoohoo.guru
title: "[Feature]: "
labels: ["enhancement", "feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We value community input in making yoohoo.guru better.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have read the contributing guidelines
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of the application would this feature affect?
      options:
        - Frontend/UI
        - Backend/API
        - Authentication
        - Skill Matching
        - Payments
        - Database
        - Mobile/Responsive
        - Community Features
        - Admin Dashboard
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for core functionality
        - Critical - Essential for platform success
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Include any mockups, examples, or additional context here...